import { StrictMode, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { Mountain } from 'lucide-react';
import { AppShell, applyTheme, CitationsProvider, readTheme, type ShellConfig, useLangStore } from '@fasl-work/caos-app-shell';
import '@fasl-work/caos-app-shell/styles.css';
import './pitforge.css';
import { CITATIONS } from './data/citations.ts';
import { architecture } from './architecture';
import Tool from './pages/Tool.tsx';
import Introduction from './pages/Introduction.tsx';
import Methodology from './pages/Methodology.tsx';
import Implementation from './pages/Implementation.tsx';
import Experiments from './pages/Experiments.tsx';
import Focus from './pages/Focus.tsx';
import Benchmark from './pages/Benchmark.tsx';

applyTheme(readTheme());

/** Keep assistive technology and browser translation aligned with the visible language. */
function DocumentLocale() {
  const lang = useLangStore((state) => state.lang);
  useEffect(() => {
    document.documentElement.lang = lang;
    document.title = lang === 'es'
      ? 'PitForge · rajo último y cáscaras anidadas'
      : 'PitForge · ultimate pit and nested shells';
  }, [lang]);
  return null;
}

const config: ShellConfig = {
  product: { name: 'PitForge', mark: <Mountain size={18} aria-hidden="true" /> },
  routes: [
    { path: '/', en: 'App', es: 'App' },
    { path: '/introduction', en: 'Introduction', es: 'Introducción' },
    { path: '/methodology', en: 'Methodology', es: 'Metodología' },
    { path: '/implementation', en: 'Implementation', es: 'Implementación' },
    { path: '/experiments', en: 'Experiments', es: 'Experimentos' },
    { path: '/benchmark', en: 'Benchmark', es: 'Benchmark' },
  ],
  links: { github: 'https://github.com/fsantibanezleal/CAOS_PitForge' },
  version: '0.13.001',
  architecture,
  // ADR-0016 §2: honest footer provenance + disclaimer.
  footer: {
    provenance: {
      en: 'Real lane: MineLib open-pit instances, CC BY-SA 3.0 Unported (Espinoza, Goycoolea, Moreno & Newman 2013, doi:10.1007/s10479-012-1258-3), fetched at runtime and not bundled by project policy. Engine: maximum closure via exact max-flow/min-cut (Picard), equivalent in optimum value to the Lerchs-Grossmann problem. Synthetic lane: seeded deposits plus MIT twins generated by oreblocks 0.1.0.',
      es: 'Carril real: instancias de rajo abierto MineLib, CC BY-SA 3.0 Unported (Espinoza, Goycoolea, Moreno & Newman 2013, doi:10.1007/s10479-012-1258-3), descargadas en tiempo de ejecución y no empaquetadas por política del proyecto. Motor: cierre máximo por max-flow/min-cut exacto (Picard), equivalente en valor óptimo al problema de Lerchs-Grossmann. Carril sintético: depósitos sembrados más gemelos MIT generados por oreblocks 0.1.0.',
    },
    disclaimer: {
      en: 'A static, in-browser mine-design workbench: no backend. The exact min-cut is the authority and reproduces the published MineLib optima live; the ONNX learned models give an instant approximate preview of the pit, with their agreement against the exact solver shown on screen; they have no effect on the exact solve and never replace it. The CPIT scheduling lane adds a certified NPV bound. Not for production mine planning.',
      es: 'Un taller de diseño minero estático en el navegador: sin backend. El min-cut exacto es la autoridad y reproduce en vivo los óptimos publicados de MineLib; los modelos ONNX aprendidos entregan una vista previa aproximada e instantánea del pit, mostrando en pantalla su acuerdo con el solver exacto; no influyen en la resolución exacta y nunca la reemplazan. El carril de scheduling CPIT agrega una cota certificada de NPV. No apto para planificación minera de producción.',
    },
  },
};

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <BrowserRouter>
      <CitationsProvider items={CITATIONS}>
        <DocumentLocale />
        <Routes>
          {/* ADR-0070: the focus view renders OUTSIDE the shell. The header and footer are exactly the
              chrome a focus view exists to escape, so it cannot be a child of AppShell. */}
          <Route path="/focus/:caseId" element={<Focus />} />
          <Route path="*" element={
        <AppShell config={config}>
          <Routes>
            <Route path="/" element={<Tool />} />
            <Route path="/introduction" element={<Introduction />} />
            <Route path="/methodology" element={<Methodology />} />
            <Route path="/implementation" element={<Implementation />} />
            <Route path="/experiments" element={<Experiments />} />
            <Route path="/benchmark" element={<Benchmark />} />
            <Route path="*" element={<Tool />} />
          </Routes>
        </AppShell>
          } />
        </Routes>
      </CitationsProvider>
    </BrowserRouter>
  </StrictMode>,
);
